# Generated by Django 5.2.10 on 2026-01-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
