# Generated by Django 5.2.10 on 2026-01-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_project_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="artifact_images/"),
        ),
    ]
