# Generated by Django 5.2.10 on 2026-01-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_artifact_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="embed_html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="project_thumbs/"),
        ),
        migrations.DeleteModel(
            name="Artifact",
        ),
    ]
