# Generated by Django 5.2.10 on 2026-01-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_project_embed_and_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="summary",
            field=models.TextField(blank=True),
        ),
    ]
