# Generated by Django 5.2.10 on 2026-01-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_project_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="embed_html",
        ),
    ]
