# Generated by Django 6.0.1 on 2026-01-27 00:00

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Project = apps.get_model("portal", "Project")
    for project in Project.objects.all():
        if project.slug:
            continue
        base_slug = slugify(project.title) or "project"
        slug = base_slug
        counter = 1
        while Project.objects.filter(slug=slug).exclude(pk=project.pk).exists():
            counter += 1
            slug = f"{base_slug}-{counter}"
        project.slug = slug
        project.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0008_project_description_markdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
                name="slug",
                field=models.SlugField(blank=True, null=True, max_length=220, unique=True),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
